[project]
name = "ala"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jacob", email = "jacob.holm.andersen29@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "ruff>=0.12.10",
]
